// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC010Fb5r92jg3TA9FPvJaj1E0fVOQC5pM',
    appId: '1:773132701720:web:04934ceb2c04237a1cf36d',
    messagingSenderId: '773132701720',
    projectId: 'notes-sharing-app-3cec7',
    authDomain: 'notes-sharing-app-3cec7.firebaseapp.com',
    storageBucket: 'notes-sharing-app-3cec7.firebasestorage.app',
    measurementId: 'G-QK7HT1EERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoOlEooMLyQbMlhd7DyAXH4f_65Wo4ZU',
    appId: '1:773132701720:android:e9188605035d8d521cf36d',
    messagingSenderId: '773132701720',
    projectId: 'notes-sharing-app-3cec7',
    storageBucket: 'notes-sharing-app-3cec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpf8JXOpufY3uM8LZxugUrh4OiD6uEaRs',
    appId: '1:773132701720:ios:c1688310bab187921cf36d',
    messagingSenderId: '773132701720',
    projectId: 'notes-sharing-app-3cec7',
    storageBucket: 'notes-sharing-app-3cec7.firebasestorage.app',
    iosBundleId: 'com.example.notesSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpf8JXOpufY3uM8LZxugUrh4OiD6uEaRs',
    appId: '1:773132701720:ios:c1688310bab187921cf36d',
    messagingSenderId: '773132701720',
    projectId: 'notes-sharing-app-3cec7',
    storageBucket: 'notes-sharing-app-3cec7.firebasestorage.app',
    iosBundleId: 'com.example.notesSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC010Fb5r92jg3TA9FPvJaj1E0fVOQC5pM',
    appId: '1:773132701720:web:b2850e60defcd4021cf36d',
    messagingSenderId: '773132701720',
    projectId: 'notes-sharing-app-3cec7',
    authDomain: 'notes-sharing-app-3cec7.firebaseapp.com',
    storageBucket: 'notes-sharing-app-3cec7.firebasestorage.app',
    measurementId: 'G-72MRDM4N2M',
  );
}
